<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{
    public function getAds()
    {
        $request = 'SELECT ad
            FROM SiteBundle:Ad ad';
        $query = $this->getEntityManager()->createQuery($request);
        return $query->getResult();
    }
}
