site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }

faq:
    path:   /faq
    defaults: { _controller: SiteBundle:Default:faq }

cgu:
    path:   /cgu
    defaults: { _controller: SiteBundle:Default:cgu }