index:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }

faq:
    path:   /faq
    defaults: { _controller: SiteBundle:Default:faq }

cgu:
    path:   /cgu
    defaults: { _controller: SiteBundle:Default:cgu }

add:
    path:   /ad/add
    defaults: { _controller: SiteBundle:Ad:add }
    
detail_ad:
    path:   /ad/detail
    defaults: { _controller: SiteBundle:Ad:detail }

list:
    path:   /ad/list
    defaults: { _controller: SiteBundle:Ad:list }
